/*
 * PanelConfig.java
 *
 * Created on September 18, 2007, 9:24 AM
 */

package mixnfix.gui;

/**
 *
 * @author  lauro
 */
public class PanelConfig extends javax.swing.JPanel {
    
    /** Creates new form PanelConfig */
    public PanelConfig() {
        initComponents();
                        
        // read config variables
        String openPDF = App.getConfiguracao().getProperty(ConfiguracaoMIXnFIX.openPDF);
        String openXLS = App.getConfiguracao().getProperty(ConfiguracaoMIXnFIX.openXLS);
        String openHTML = App.getConfiguracao().getProperty(ConfiguracaoMIXnFIX.openHTML);
        String convertEPS2PDF = App.getConfiguracao().getProperty(ConfiguracaoMIXnFIX.convertEPS2PDF);
        String compileTEX2PDF = App.getConfiguracao().getProperty(ConfiguracaoMIXnFIX.compileTEX2PDF);
        String triangulate = App.getConfiguracao().getProperty(ConfiguracaoMIXnFIX.triangulate);

        //
        _tfOpenPDF.setText(openPDF);
        _tfOpenXLS.setText(openXLS);
        _tfOpenHTML.setText(openHTML);
        _tfTriangulate.setText(triangulate);
        _tfConvertEPS2PDF.setText(convertEPS2PDF);
        _taCompileTEX2PDF.setText(compileTEX2PDF);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        _tfConvertEPS2PDF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _taCompileTEX2PDF = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        _tfOpenPDF = new javax.swing.JTextField();
        _btnOK = new javax.swing.JButton();
        _btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        _tfOpenXLS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        _tfOpenHTML = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        _tfTriangulate = new javax.swing.JTextField();

        jLabel1.setText("Convert .eps file to .pdf (context: $epsfile)");

        _tfConvertEPS2PDF.setText("eps2pdf $epsfile");

        jLabel2.setText("Compile .tex to .pdf (context: $texfile, $sourcedir, $outputdir)   (newline will be replaced by space)");

        _taCompileTEX2PDF.setColumns(20);
        _taCompileTEX2PDF.setRows(5);
        _taCompileTEX2PDF.setText("pdflatex -halt-on-error\n     -include-directory=$sourcedir\n     -output-directory=$outputdir\n     -aux-directory=$sourcedir\n     $texfile");
        jScrollPane1.setViewportView(_taCompileTEX2PDF);

        jLabel3.setText("Open .pdf (context: $pdffile)");

        _tfOpenPDF.setText("evince $pdffile");

        _btnOK.setText("OK");
        _btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnOKActionPerformed(evt);
            }
        });

        _btnCancel.setText("Cancelar");
        _btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Open .xls (context: $xlsfile)");

        _tfOpenXLS.setText("ooffice $xlsfile");

        jLabel5.setText("Open .html (context: $htmlfile)");

        _tfOpenHTML.setText("firefox $htmlfile");

        jLabel6.setText("Triangulate command (context: $file)  -  obs: p<time>.nodes -> p<time>.1.ele");

        _tfTriangulate.setText("t $file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(_tfOpenPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                            .addComponent(_tfOpenXLS, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(_tfOpenHTML, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(_tfConvertEPS2PDF, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(_btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btnCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(_tfTriangulate, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_btnCancel, _btnOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tfOpenPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tfOpenXLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tfOpenHTML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tfConvertEPS2PDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tfTriangulate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btnCancel)
                    .addComponent(_btnOK))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void _btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnCancelActionPerformed
        //
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event__btnCancelActionPerformed


    private void _btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnOKActionPerformed
        // TODO check input
   
        // update configuration
        App.getConfiguracao().setProperty(ConfiguracaoMIXnFIX.openPDF,_tfOpenPDF.getText());
        App.getConfiguracao().setProperty(ConfiguracaoMIXnFIX.openXLS,_tfOpenXLS.getText());
        App.getConfiguracao().setProperty(ConfiguracaoMIXnFIX.openHTML,_tfOpenHTML.getText());
        App.getConfiguracao().setProperty(ConfiguracaoMIXnFIX.convertEPS2PDF,_tfConvertEPS2PDF.getText());
        App.getConfiguracao().setProperty(ConfiguracaoMIXnFIX.compileTEX2PDF,_taCompileTEX2PDF.getText());
        App.getConfiguracao().setProperty(ConfiguracaoMIXnFIX.triangulate,_tfTriangulate.getText());
        
        //
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event__btnOKActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnCancel;
    private javax.swing.JButton _btnOK;
    private javax.swing.JTextArea _taCompileTEX2PDF;
    private javax.swing.JTextField _tfConvertEPS2PDF;
    private javax.swing.JTextField _tfOpenHTML;
    private javax.swing.JTextField _tfOpenPDF;
    private javax.swing.JTextField _tfOpenXLS;
    private javax.swing.JTextField _tfTriangulate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
