package mixnfix.modelo;

import java.sql.SQLException;
import java.util.Vector;

public interface Repositorio {
	public Instituicao consultarInstituicao(int id_instituicao) throws SQLException;
	public Instituicao inserirInstituicao(Instituicao obj) throws SQLException;
	public Instituicao inserirInstituicao(String nome) throws SQLException;
	public void removerInstituicao(Instituicao obj) throws SQLException;
	public void removerInstituicao(int id_instituicao) throws SQLException;
	public void atualizarNomeEmInstituicao(Instituicao instituicao, String nome) throws SQLException;
	public Vector consultarInstituicao() throws SQLException;
	public Periodo consultarPeriodo(String id_periodo) throws SQLException;
	public Periodo inserirPeriodo(Periodo obj) throws SQLException;
	public Periodo inserirPeriodo(String id_periodo) throws SQLException;
	public void removerPeriodo(Periodo obj) throws SQLException;
	public void removerPeriodo(String id_periodo) throws SQLException;
	public void atualizarId_periodoEmPeriodo(Periodo periodo, String id_periodo) throws SQLException;
	public Vector consultarPeriodo() throws SQLException;
	public Turma consultarTurma(int id_turma) throws SQLException;
	public Turma inserirTurma(Turma obj) throws SQLException;
	public Turma inserirTurma(String nome, Instituicao instituicao_Turma) throws SQLException;
	public void removerTurma(Turma obj) throws SQLException;
	public void removerTurma(int id_turma) throws SQLException;
	public void atualizarNomeEmTurma(Turma turma, String nome) throws SQLException;
	public Vector consultarTurma() throws SQLException;
	public Vector consultarTurmaPorInstituicao(Instituicao instituicao_Turma) throws SQLException;
	public Vector consultarTurmaPorInstituicaoNome(String nome, Instituicao instituicao_Turma) throws SQLException;
	public void atualizarInstituicao_TurmaEmTurma(Turma turma, Instituicao instituicao_Turma) throws SQLException;
	public Aluno consultarAluno(int id_aluno) throws SQLException;
	public Aluno inserirAluno(Aluno obj) throws SQLException;
	public Aluno inserirAluno(String nome, String matricula, Instituicao instituicao_Aluno) throws SQLException;
	public void removerAluno(Aluno obj) throws SQLException;
	public void removerAluno(int id_aluno) throws SQLException;
	public void atualizarNomeEmAluno(Aluno aluno, String nome) throws SQLException;
	public void atualizarMatriculaEmAluno(Aluno aluno, String matricula) throws SQLException;
	public Vector consultarAluno() throws SQLException;
	public Vector consultarAlunoPorMatricula(String matricula) throws SQLException;
	public Vector consultarAlunoPorInstituicao(Instituicao instituicao_Aluno) throws SQLException;
	public void atualizarInstituicao_AlunoEmAluno(Aluno aluno, Instituicao instituicao_Aluno) throws SQLException;
	public Curso consultarCurso(int id_curso) throws SQLException;
	public Curso inserirCurso(Curso obj) throws SQLException;
	public Curso inserirCurso(String nome, Instituicao instituicao_Curso) throws SQLException;
	public void removerCurso(Curso obj) throws SQLException;
	public void removerCurso(int id_curso) throws SQLException;
	public void atualizarNomeEmCurso(Curso curso, String nome) throws SQLException;
	public Vector consultarCurso() throws SQLException;
	public Vector consultarCursoPorInstituicao(Instituicao instituicao_Curso) throws SQLException;
	public void atualizarInstituicao_CursoEmCurso(Curso curso, Instituicao instituicao_Curso) throws SQLException;
	public AlunoTurma consultarAlunoTurma(int id_aluno, int id_turma) throws SQLException;
	public AlunoTurma inserirAlunoTurma(AlunoTurma obj) throws SQLException;
	public AlunoTurma inserirAlunoTurma(Aluno aluno_AlunoTurma, Turma turma_AlunoTurma) throws SQLException;
	public void removerAlunoTurma(AlunoTurma obj) throws SQLException;
	public void removerAlunoTurma(int id_aluno, int id_turma) throws SQLException;
	public Vector consultarAlunoTurma() throws SQLException;
	public Vector consultarAlunoTurmaPorTurma(Turma turma_AlunoTurma) throws SQLException;
	public Vector consultarAlunoTurmaPorAluno(Aluno aluno_AlunoTurma) throws SQLException;
	public void atualizarAluno_AlunoTurmaEmAlunoTurma(AlunoTurma alunoTurma, Aluno aluno_AlunoTurma) throws SQLException;
	public void atualizarTurma_AlunoTurmaEmAlunoTurma(AlunoTurma alunoTurma, Turma turma_AlunoTurma) throws SQLException;
	public CursoInstancia consultarCursoInstancia(int id_cursoinstancia) throws SQLException;
	public CursoInstancia inserirCursoInstancia(CursoInstancia obj) throws SQLException;
	public CursoInstancia inserirCursoInstancia(Instituicao instituicao_CursoInstancia, Curso curso_CursoInstancia, Periodo periodo_CursoInstancia) throws SQLException;
	public void removerCursoInstancia(CursoInstancia obj) throws SQLException;
	public void removerCursoInstancia(int id_cursoinstancia) throws SQLException;
	public Vector consultarCursoInstancia() throws SQLException;
	public Vector consultarCursoInstanciaPorInstituicao(Instituicao instituicao_CursoInstancia) throws SQLException;
	public Vector consultarCursoInstanciaPorCurso(Curso curso_CursoInstancia) throws SQLException;
	public Vector consultarCursoInstanciaPorPeriodo(Periodo periodo_CursoInstancia) throws SQLException;
	public void atualizarInstituicao_CursoInstanciaEmCursoInstancia(CursoInstancia cursoInstancia, Instituicao instituicao_CursoInstancia) throws SQLException;
	public void atualizarCurso_CursoInstanciaEmCursoInstancia(CursoInstancia cursoInstancia, Curso curso_CursoInstancia) throws SQLException;
	public void atualizarPeriodo_CursoInstanciaEmCursoInstancia(CursoInstancia cursoInstancia, Periodo periodo_CursoInstancia) throws SQLException;
	public AlunoCursoInstancia consultarAlunoCursoInstancia(int id_alunocursoinstancia) throws SQLException;
	public AlunoCursoInstancia inserirAlunoCursoInstancia(AlunoCursoInstancia obj) throws SQLException;
	public AlunoCursoInstancia inserirAlunoCursoInstancia(CursoInstancia cursoInstancia_AlunoCursoInstancia, Aluno aluno_AlunoCursoInstancia) throws SQLException;
	public void removerAlunoCursoInstancia(AlunoCursoInstancia obj) throws SQLException;
	public void removerAlunoCursoInstancia(int id_alunocursoinstancia) throws SQLException;
	public Vector consultarAlunoCursoInstancia() throws SQLException;
	public Vector consultarAlunoCursoInstanciaPorCursoInstancia(CursoInstancia cursoInstancia_AlunoCursoInstancia) throws SQLException;
	public Vector consultarAlunoCursoInstanciaPorAluno(Aluno aluno_AlunoCursoInstancia) throws SQLException;
	public void atualizarCursoInstancia_AlunoCursoInstanciaEmAlunoCursoInstancia(AlunoCursoInstancia alunoCursoInstancia, CursoInstancia cursoInstancia_AlunoCursoInstancia) throws SQLException;
	public void atualizarAluno_AlunoCursoInstanciaEmAlunoCursoInstancia(AlunoCursoInstancia alunoCursoInstancia, Aluno aluno_AlunoCursoInstancia) throws SQLException;
	public Avaliacao consultarAvaliacao(int id_avaliacao) throws SQLException;
	public Avaliacao inserirAvaliacao(Avaliacao obj) throws SQLException;
	public Avaliacao inserirAvaliacao(String nome, String tipo, CursoInstancia cursoInstancia_Avaliacao) throws SQLException;
	public void removerAvaliacao(Avaliacao obj) throws SQLException;
	public void removerAvaliacao(int id_avaliacao) throws SQLException;
	public void atualizarNomeEmAvaliacao(Avaliacao avaliacao, String nome) throws SQLException;
	public void atualizarTipoEmAvaliacao(Avaliacao avaliacao, String tipo) throws SQLException;
	public Vector consultarAvaliacao() throws SQLException;
	public Vector consultarAvaliacaoPorTipo(String tipo) throws SQLException;
	public Vector consultarAvaliacaoPorCursoInstancia(CursoInstancia cursoInstancia_Avaliacao) throws SQLException;
	public void atualizarCursoInstancia_AvaliacaoEmAvaliacao(Avaliacao avaliacao, CursoInstancia cursoInstancia_Avaliacao) throws SQLException;
	public AvaliacaoAluno consultarAvaliacaoAluno(int id_avaliacaoaluno) throws SQLException;
	public AvaliacaoAluno inserirAvaliacaoAluno(AvaliacaoAluno obj) throws SQLException;
	public AvaliacaoAluno inserirAvaliacaoAluno(float nota, String noTotalizado, Avaliacao avaliacao_AvaliacaoAluno, Correcao correcao_AvaliacaoAluno, AlunoCursoInstancia alunoCursoInstancia_AvaliacaoAluno) throws SQLException;
	public void removerAvaliacaoAluno(AvaliacaoAluno obj) throws SQLException;
	public void removerAvaliacaoAluno(int id_avaliacaoaluno) throws SQLException;
	public void atualizarNotaEmAvaliacaoAluno(AvaliacaoAluno avaliacaoAluno, float nota) throws SQLException;
	public void atualizarNoTotalizadoEmAvaliacaoAluno(AvaliacaoAluno avaliacaoAluno, String noTotalizado) throws SQLException;
	public Vector consultarAvaliacaoAluno() throws SQLException;
	public Vector consultarAvaliacaoAlunoPorAvaliacao(Avaliacao avaliacao_AvaliacaoAluno) throws SQLException;
	public Vector consultarAvaliacaoAlunoPorCorrecao(Correcao correcao_AvaliacaoAluno) throws SQLException;
	public Vector consultarAvaliacaoAlunoPorAlunoCursoInstancia(AlunoCursoInstancia alunoCursoInstancia_AvaliacaoAluno) throws SQLException;
	public void atualizarAvaliacao_AvaliacaoAlunoEmAvaliacaoAluno(AvaliacaoAluno avaliacaoAluno, Avaliacao avaliacao_AvaliacaoAluno) throws SQLException;
	public void atualizarCorrecao_AvaliacaoAlunoEmAvaliacaoAluno(AvaliacaoAluno avaliacaoAluno, Correcao correcao_AvaliacaoAluno) throws SQLException;
	public void atualizarAlunoCursoInstancia_AvaliacaoAlunoEmAvaliacaoAluno(AvaliacaoAluno avaliacaoAluno, AlunoCursoInstancia alunoCursoInstancia_AvaliacaoAluno) throws SQLException;
	public Prova consultarProva(int id_prova) throws SQLException;
	public Prova inserirProva(Prova obj) throws SQLException;
	public Prova inserirProva(String nome, String fonte, int indice, Instituicao instituicao_Prova) throws SQLException;
	public void removerProva(Prova obj) throws SQLException;
	public void removerProva(int id_prova) throws SQLException;
	public void atualizarNomeEmProva(Prova prova, String nome) throws SQLException;
	public void atualizarFonteEmProva(Prova prova, String fonte) throws SQLException;
	public void atualizarIndiceEmProva(Prova prova, int indice) throws SQLException;
	public Vector consultarProva() throws SQLException;
	public Vector consultarProvaPorInstituicao(Instituicao instituicao_Prova) throws SQLException;
	public void atualizarInstituicao_ProvaEmProva(Prova prova, Instituicao instituicao_Prova) throws SQLException;
	public Correcao consultarCorrecao(int id_correcao) throws SQLException;
	public Correcao inserirCorrecao(Correcao obj) throws SQLException;
	public Correcao inserirCorrecao(String matriz, String imagem, float nota, Prova prova_Correcao, Aluno aluno_Correcao) throws SQLException;
	public void removerCorrecao(Correcao obj) throws SQLException;
	public void removerCorrecao(int id_correcao) throws SQLException;
	public void atualizarMatrizEmCorrecao(Correcao correcao, String matriz) throws SQLException;
	public void atualizarImagemEmCorrecao(Correcao correcao, String imagem) throws SQLException;
	public void atualizarNotaEmCorrecao(Correcao correcao, float nota) throws SQLException;
	public Vector consultarCorrecao() throws SQLException;
	public Vector consultarCorrecaoPorAluno(Aluno aluno_Correcao) throws SQLException;
	public Vector consultarCorrecaoPorProva(Prova prova_Correcao) throws SQLException;
	public void atualizarProva_CorrecaoEmCorrecao(Correcao correcao, Prova prova_Correcao) throws SQLException;
	public void atualizarAluno_CorrecaoEmCorrecao(Correcao correcao, Aluno aluno_Correcao) throws SQLException;
	public ProvaCorrecao consultarProvaCorrecao(int id_provacorrecao) throws SQLException;
	public ProvaCorrecao inserirProvaCorrecao(ProvaCorrecao obj) throws SQLException;
	public ProvaCorrecao inserirProvaCorrecao(String nome, Prova prova_ProvaCorrecao) throws SQLException;
	public void removerProvaCorrecao(ProvaCorrecao obj) throws SQLException;
	public void removerProvaCorrecao(int id_provacorrecao) throws SQLException;
	public void atualizarNomeEmProvaCorrecao(ProvaCorrecao provaCorrecao, String nome) throws SQLException;
	public Vector consultarProvaCorrecao() throws SQLException;
	public Vector consultarProvaCorrecaoPorProva(Prova prova_ProvaCorrecao) throws SQLException;
	public void atualizarProva_ProvaCorrecaoEmProvaCorrecao(ProvaCorrecao provaCorrecao, Prova prova_ProvaCorrecao) throws SQLException;
	public AlunoProvaCorrecao consultarAlunoProvaCorrecao(int id_aluno, int id_provacorrecao) throws SQLException;
	public AlunoProvaCorrecao inserirAlunoProvaCorrecao(AlunoProvaCorrecao obj) throws SQLException;
	public AlunoProvaCorrecao inserirAlunoProvaCorrecao(int numEntradas, Aluno aluno_AlunoProvaCorrecao, ProvaCorrecao provaCorrecao_AlunoProvaCorrecao) throws SQLException;
	public void removerAlunoProvaCorrecao(AlunoProvaCorrecao obj) throws SQLException;
	public void removerAlunoProvaCorrecao(int id_aluno, int id_provacorrecao) throws SQLException;
	public void atualizarNumEntradasEmAlunoProvaCorrecao(AlunoProvaCorrecao alunoProvaCorrecao, int numEntradas) throws SQLException;
	public Vector consultarAlunoProvaCorrecao() throws SQLException;
	public Vector consultarAlunoProvaCorrecaoPorProvaCorrecao(ProvaCorrecao provaCorrecao_AlunoProvaCorrecao) throws SQLException;
	public void atualizarAluno_AlunoProvaCorrecaoEmAlunoProvaCorrecao(AlunoProvaCorrecao alunoProvaCorrecao, Aluno aluno_AlunoProvaCorrecao) throws SQLException;
	public void atualizarProvaCorrecao_AlunoProvaCorrecaoEmAlunoProvaCorrecao(AlunoProvaCorrecao alunoProvaCorrecao, ProvaCorrecao provaCorrecao_AlunoProvaCorrecao) throws SQLException;
	public EntradaProvaCorrecao consultarEntradaProvaCorrecao(int id_entradaprovacorrecao) throws SQLException;
	public EntradaProvaCorrecao inserirEntradaProvaCorrecao(EntradaProvaCorrecao obj) throws SQLException;
	public EntradaProvaCorrecao inserirEntradaProvaCorrecao(byte status, String foto, int threshold, int phase, int idImageData, int tipo, int idAnswersData, ProvaCorrecao provaCorrecao_EntradaProvaCorrecao, Aluno aluno_EntradaProvaCorrecao) throws SQLException;
	public void removerEntradaProvaCorrecao(EntradaProvaCorrecao obj) throws SQLException;
	public void removerEntradaProvaCorrecao(int id_entradaprovacorrecao) throws SQLException;
	public void atualizarStatusEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, byte status) throws SQLException;
	public void atualizarFotoEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, String foto) throws SQLException;
	public void atualizarThresholdEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, int threshold) throws SQLException;
	public void atualizarPhaseEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, int phase) throws SQLException;
	public void atualizarIdImageDataEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, int idImageData) throws SQLException;
	public void atualizarTipoEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, int tipo) throws SQLException;
	public void atualizarIdAnswersDataEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, int idAnswersData) throws SQLException;
	public Vector consultarEntradaProvaCorrecao() throws SQLException;
	public Vector consultarEntradaProvaCorrecaoporProvaCorrecao(ProvaCorrecao provaCorrecao_EntradaProvaCorrecao) throws SQLException;
	public void atualizarProvaCorrecao_EntradaProvaCorrecaoEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, ProvaCorrecao provaCorrecao_EntradaProvaCorrecao) throws SQLException;
	public void atualizarAluno_EntradaProvaCorrecaoEmEntradaProvaCorrecao(EntradaProvaCorrecao entradaProvaCorrecao, Aluno aluno_EntradaProvaCorrecao) throws SQLException;
	public ColetaQuestionario consultarColetaQuestionario(int id_coletaquestionario) throws SQLException;
	public ColetaQuestionario inserirColetaQuestionario(ColetaQuestionario obj) throws SQLException;
	public ColetaQuestionario inserirColetaQuestionario(String nome, Prova prova_ColetaQuestionario) throws SQLException;
	public void removerColetaQuestionario(ColetaQuestionario obj) throws SQLException;
	public void removerColetaQuestionario(int id_coletaquestionario) throws SQLException;
	public void atualizarNomeEmColetaQuestionario(ColetaQuestionario coletaQuestionario, String nome) throws SQLException;
	public Vector consultarColetaQuestionario() throws SQLException;
	public Vector consultarColetaQuestionarioPorProva(Prova prova_ColetaQuestionario) throws SQLException;
	public void atualizarProva_ColetaQuestionarioEmColetaQuestionario(ColetaQuestionario coletaQuestionario, Prova prova_ColetaQuestionario) throws SQLException;
	public EntradaColetaQuestionario consultarEntradaColetaQuestionario(int id_entradacoletaquestionario) throws SQLException;
	public EntradaColetaQuestionario inserirEntradaColetaQuestionario(EntradaColetaQuestionario obj) throws SQLException;
	public EntradaColetaQuestionario inserirEntradaColetaQuestionario(byte status, String foto, int threshold, int phase, int idImageData, int tipoFolhaResposta, int idAnswersData, ColetaQuestionario coletaQuestionario_EntradaColetaQuestionario) throws SQLException;
	public void removerEntradaColetaQuestionario(EntradaColetaQuestionario obj) throws SQLException;
	public void removerEntradaColetaQuestionario(int id_entradacoletaquestionario) throws SQLException;
	public void atualizarStatusEmEntradaColetaQuestionario(EntradaColetaQuestionario entradaColetaQuestionario, byte status) throws SQLException;
	public void atualizarFotoEmEntradaColetaQuestionario(EntradaColetaQuestionario entradaColetaQuestionario, String foto) throws SQLException;
	public void atualizarThresholdEmEntradaColetaQuestionario(EntradaColetaQuestionario entradaColetaQuestionario, int threshold) throws SQLException;
	public void atualizarPhaseEmEntradaColetaQuestionario(EntradaColetaQuestionario entradaColetaQuestionario, int phase) throws SQLException;
	public void atualizarIdImageDataEmEntradaColetaQuestionario(EntradaColetaQuestionario entradaColetaQuestionario, int idImageData) throws SQLException;
	public void atualizarTipoFolhaRespostaEmEntradaColetaQuestionario(EntradaColetaQuestionario entradaColetaQuestionario, int tipoFolhaResposta) throws SQLException;
	public void atualizarIdAnswersDataEmEntradaColetaQuestionario(EntradaColetaQuestionario entradaColetaQuestionario, int idAnswersData) throws SQLException;
	public Vector consultarEntradaColetaQuestionario() throws SQLException;
	public Vector consultarEntradaColetaQuestionarioPorColetaQuestionario(ColetaQuestionario coletaQuestionario_EntradaColetaQuestionario) throws SQLException;
	public void atualizarColetaQuestionario_EntradaColetaQuestionarioEmEntradaColetaQuestionario(EntradaColetaQuestionario entradaColetaQuestionario, ColetaQuestionario coletaQuestionario_EntradaColetaQuestionario) throws SQLException;
}
